#!/bin/bash

set -ex

branch=`git branch | grep -e "^*" | cut -d' ' -f 2`

git checkout master
git merge "$branch"
RAILS_ENV=production bundle exec rake assets:precompile
git add .
git commit -m "autobuild `date "+%Y%m%d`"
git push origin master
git checkout "$branch"
git merge master

