#!/usr/bin/env ruby

def puts! a, b=''
  puts "+++ +++ #{b}"
  puts a.inspect
end

a = `systemctl status m3_manager.service | grep "Active: activ"`
b = $?.exitstatus

if b.to_i == 1
  puts "service not running!"
else
  puts "service ok"
end

exit b
