#!/bin/bash

set -ex

cd /home/ubuntu/projects/microsites3_manager
git reset origin/master --hard
git pull

sudo service microsites3_manager-app restart
sleep 3
sudo service microsites3_manager-app status

